### ISSUE TITLE
enhanced bit rate pop-up causing no resolution selection

### ISSUE THREAD

**Issue by Windows200000** [fiahfy/youtube-video-quality-fixer#26]
This extension is causing a YouTube premium pop-up, every time a video with an enhanced bit rate option loads.
![image](https://github.com/fiahfy/youtube-video-quality-fixer/assets/72623832/127fb80d-122a-48dc-a6aa-e1f271a1474d)

[example for testing](https://www.youtube.com/watch?v=BHACKCNDMW8)

edit: This also causes the highest bit rate not be selected, as I have to decline the enhanced bit rate, reversing the selection to auto.

**Comment by fiahfy** [comment]
Ignore the premium bitrate option in version [v0.0.11](https://github.com/fiahfy/youtube-video-quality-fixer/releases/tag/v0.0.11).
Thank you!
