### ISSUE TITLE
Pick Enhanced Bitrate when using YouTube Premium

### ISSUE THREAD

**Issue by smhmd** [fiahfy/youtube-video-quality-fixer#31]
Thanks for the helpful extension.

When using YT Premium, you also have access to "enhanced bitrate" (whatever that is) and I believe it'd be great if that's picked up over the normal resolution.

<img width="264" alt="image" src="https://github.com/fiahfy/youtube-video-quality-fixer/assets/46059092/7382cb20-e118-4a8d-9be0-06c4ead04930">

**Comment by GKid94** [comment]
Better to add Use enhanced bitrate by default option without Premium

**Comment by fiahfy** [comment]
fixed it in the latest version
https://github.com/fiahfy/youtube-video-quality-fixer/releases/tag/v0.0.12
