### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by camjac251** [fiahfy/youtube-video-quality-fixer#9]
Would it be possible to support Firefox as well?

**Comment by fiahfy** [comment]
There are no plans to publish to Firefox Add-ons.
You can unzip the `archive.zip` on the release page and load it as a temporary plugin.

**Comment by camjac251** [comment]
Do you mainly use Chrome? Would a maintainer be needed for the Firefox version? Addons require signing with Firefox and Chrome for them to work as intended. Chrome displays a message when developer mode is enabled and an unsigned addon is used and Firefox will refuse any unsigned addons for security purposes.

**Comment by fiahfy** [comment]
In order to use extension permanently in Firefox, you need to publish it to Firefox Add-ons or sign it, but there is no plan to support both.
